#!/bin/bash
RES=~/.config/PrusaSlicer/resources
shopt -s extglob
set -eu
./parseprusa.py "$@" --list | sed -ne 's/^\(printer:Original Prusa XL .*Input Shaper\)/\1/p;s/^\(print:.* @XLIS\)/\1/p;s/^\(filament:.* @XL\)/\1/p' |
	while read i; do
		echo >&2 "[gens] $i"
		./parseprusa.py "$@" "$i" | sed -ne "s|.*printer_notes!~/\.\*XLIS.*||;s/^\(compatible_printers_condition = .*\)XL[IS]*\(.*\)$/[${i/@(XL|XLIS)/VORON}]\ninherits = ${i/@(print|filament):}; *Voron*\n\1VORON\2\n/p"
	done
for t in 250 300 350; do
	echo >&2 "[gens] printer:*resources$t*"
	cat <<EOF
[printer:*resources$t*]
bed_custom_model = $RES/voronbed$t.stl
bed_custom_texture = $RES/voronbed$t.svg

EOF
done
