#!/bin/bash
set -eu
rm -rf out
mkdir out{,/print,/filament,/printer,/resources}
./parseprusa.py "$@" --list | sed -ne 's/^printer:Original Prusa XL - 5T Input Shaper \(.*\)/printer:Voron 250 \1\nprinter:Voron 300 \1\nprinter:Voron 350 \1/p;s/^\(print:.*\) @XLIS/\1 @VORON/p;s/^\(filament:.*\) @XL[IS]*/\1 @VORON/p' |
       	while read i; do
		echo "[genvoron] $i"
		./parseprusa.py "$@" "$i" > "out/${i/://}.ini"
	done
for type in 250 300 350; do
	echo "[genvoron] resources:$type"
	openscad bed.scad -Dtype=$type --export-format binstl -o out/resources/voronbed$type.stl 3>&1 1>&2 2>&3 | sed -ne 's/ECHO: "\(.*\)"/\1/p' > out/resources/voronbed$type.svg
done
