#!/usr/bin/env python3

import sys

currentsection = None
data = {}
mysection = {}
for file in sys.argv[1:-1]:
    with open(file, 'r') as f:
        for line in f:
            if line[-1] == '\n':
                line = line[:-1]
            if len(line.strip()) == 0:
                continue
            if line[0] in '#;':
                continue
            if line[0] == '[':
                if line[-1] == ']':
                    currentsection = line[1:-1]
                    data[currentsection] = {}
                    continue
                else:
                    raise ValueError
            key, value = line.split('=', 1)
            data[currentsection][key.strip()] = value.lstrip()

def fillsection(section):
    if 'inherits' in data[section] and data[section]['inherits'] != '':
        for inh in data[section]['inherits'].split(';'):
            fillsection(f'{ctype}:{inh.strip()}')
    for key, value in data[section].items():
        mysection[key] = value

if sys.argv[-1] == '--list':
    for section in data.keys():
        if section[-1] == '*':
            continue
        if section.split(':')[0] not in [ 'printer', 'filament', 'print' ]:
            continue
        print(f'{section}')
    exit(0)
ctype, cname = sys.argv[-1].split(':')

fillsection(f'{ctype}:*DEFAULTS*')
fillsection(f'{ctype}:{cname}')
mysection['inherits'] = ''

if ctype == 'printer':
    numextruders = int(mysection['num_nozzles']) \
            if 'num_nozzles' in mysection else \
            len(mysection['nozzle_diameter'].split(
                data['printer:*MULTEXTRUDERS*']['nozzle_diameter']))
    for key in data['printer:*MULTEXTRUDERS*'].keys():
        elems = str(mysection[key]).split(data['printer:*MULTEXTRUDERS*'][key])
        while len(elems) < numextruders:
            elems.append(elems[0])
        elems = elems[:numextruders]
        mysection[key] = data['printer:*MULTEXTRUDERS*'][key].join(elems)
    numspeeds = 2 if mysection['silent_mode'] == '1' else 1
    for key in data['printer:*MULTSPEEDS*'].keys():
        elems = str(mysection[key]).split(data['printer:*MULTSPEEDS*'][key])
        while len(elems) < numspeeds:
            elems.append(elems[0])
        elems = elems[:numspeeds]
        mysection[key] = data['printer:*MULTSPEEDS*'][key].join(elems)
for key in data['*OBSOLETE*'].keys():
    mysection.pop(key, None)
for key in data['*SUFFIX*'].keys():
    if key in mysection and mysection[key][-1] != data['*SUFFIX*'][key]:
        mysection[key] += data['*SUFFIX*'][key]
print(f'# generated by prusa2voron')
for key in sorted(mysection.keys()):
    print(f'{key} = {mysection[key]}')
